#!/usr/bin/env bash
# NeoHive Smart Recall — UserPromptSubmit hook
# Generated by /neohive:generate-post-submit-hook
#
# Flow per prompt:
#   1. Read the user's prompt from stdin
#   2. Apply the trigger policy (below) — exit 0 silently if not triggered
#   3. Ask a small model to rewrite the prompt into a good memory_recall query
#   4. Call memory_recall via MCP JSON-RPC
#   5. Ask the small model to pick the 1–3 most relevant results and format them
#   6. Emit the formatted block so Claude sees it as context
#
# TEMPLATE PLACEHOLDERS (replace at generation time):
#   __HIVE__          — hive slug, or empty string for cross-hive search
#   __MODEL__         — model id for the query rewriter (e.g. claude-haiku-4-5)
#   __TRIGGER__       — trigger policy: always | min_len | keyword | manual
#   __KEYWORDS__      — pipe-delimited keywords if trigger=keyword
#   __DISABLE_FLAG__  — env var that disables the hook when set to 1

set -uo pipefail

DISABLE_FLAG="__DISABLE_FLAG__"
if [ "${!DISABLE_FLAG:-}" = "1" ]; then
  exit 0
fi

INPUT=$(cat)

# ── Extract user message ──────────────────────────────────────────────
USER_MSG=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    d = json.loads(sys.stdin.read())
except Exception:
    d = {}
msg = d.get('user_message') or d.get('message') or d.get('prompt') or ''
print(msg[:2000])
" 2>/dev/null) || exit 0

# ── Apply trigger policy ──────────────────────────────────────────────
TRIGGER="__TRIGGER__"
case "$TRIGGER" in
  always)
    ;;
  min_len)
    [ ${#USER_MSG} -lt 10 ] && exit 0
    [[ "$USER_MSG" == /* ]] && exit 0
    ;;
  keyword)
    KEYWORDS="__KEYWORDS__"
    if ! grep -qiE "(${KEYWORDS})" <<< "$USER_MSG"; then
      exit 0
    fi
    ;;
  manual)
    [ "${NEOHIVE_SMART_RUN:-}" = "1" ] || exit 0
    ;;
esac

# ── Prerequisites ─────────────────────────────────────────────────────
if [ -z "${ANTHROPIC_API_KEY:-}" ]; then
  exit 0
fi
command -v claude >/dev/null 2>&1 || exit 0
command -v curl >/dev/null 2>&1 || exit 0

MODEL="__MODEL__"
HIVE="__HIVE__"

# ── Step 1: Rewrite prompt into a memory_recall query ─────────────────
REWRITE_PROMPT="You are a query rewriter for a semantic memory system. Given a user prompt, produce a single-line search query that would retrieve relevant stored knowledge. Use affirmative domain terms, not questions. Output ONLY the query, no preamble, no quotes. Prompt: $USER_MSG"

QUERY=$(claude -p "$REWRITE_PROMPT" --model "$MODEL" --output-format text 2>/dev/null | head -c 400) || exit 0
[ -z "$QUERY" ] && exit 0

# ── Step 2: Discover MCP URL ──────────────────────────────────────────
MCP_URL=""
discover_url() {
  python3 -c "
import sys, json
try:
    d = json.loads(sys.stdin.read())
    for key, val in d.get('mcpServers', {}).items():
        k = key.lower()
        if ('neohive' in k or 'hivemind' in k) and isinstance(val, dict):
            url = val.get('url', '')
            if url:
                print(url); break
except Exception:
    pass
" 2>/dev/null
}

[ -f "mcp.json" ] && MCP_URL=$(discover_url < mcp.json)
[ -z "$MCP_URL" ] && [ -f ".mcp.json" ] && MCP_URL=$(discover_url < .mcp.json)
[ -z "$MCP_URL" ] && [ -f "$HOME/.cursor/mcp.json" ] && MCP_URL=$(discover_url < "$HOME/.cursor/mcp.json")
[ -z "$MCP_URL" ] && [ -f "$HOME/.claude.json" ] && MCP_URL=$(discover_url < "$HOME/.claude.json")
[ -z "$MCP_URL" ] && exit 0

# ── Step 3: Call memory_recall ────────────────────────────────────────
PAYLOAD=$(python3 -c "
import sys, json
args = {'query': sys.argv[1], 'limit': 8}
hive = sys.argv[2]
if hive:
    args['hive'] = hive
print(json.dumps({
    'jsonrpc': '2.0', 'id': 1, 'method': 'tools/call',
    'params': {'name': 'memory_recall', 'arguments': args}
}))
" "$QUERY" "$HIVE") || exit 0

CURL_ARGS=(-s --connect-timeout 3 --max-time 8 -X POST "$MCP_URL"
           -H "Content-Type: application/json"
           -H "Accept: application/json, text/event-stream")
[ -n "${NEOHIVE_TOKEN:-}" ] && CURL_ARGS+=(-H "Authorization: Bearer $NEOHIVE_TOKEN")

RESPONSE=$(curl "${CURL_ARGS[@]}" -d "$PAYLOAD" 2>/dev/null) || exit 0

RAW_MEMORIES=$(echo "$RESPONSE" | python3 -c "
import sys, json
try:
    raw = sys.stdin.read().strip()
    payload = None
    for line in raw.splitlines():
        if line.startswith('data: '):
            payload = line[6:]; break
    if payload is None:
        payload = raw
    d = json.loads(payload)
    texts = [c.get('text','') for c in d.get('result',{}).get('content',[]) if c.get('type')=='text']
    combined = '\n'.join(texts)
    if combined and 'No relevant memories found' not in combined:
        print(combined[:6000])
except Exception:
    pass
" 2>/dev/null) || exit 0

[ -z "$RAW_MEMORIES" ] && exit 0

# ── Step 4: Ask small model to filter + format ────────────────────────
FILTER_PROMPT=$(cat <<EOF
You are filtering memory_recall results for relevance to the user's actual prompt.

User prompt: $USER_MSG
Rewritten query: $QUERY

Memory results:
$RAW_MEMORIES

Pick the 1–3 items most relevant to the user's prompt. If none are genuinely relevant, output exactly "IRRELEVANT". Otherwise output a compact markdown block:

- <1-line summary of memory> (importance: N, type: <type>)
  <2-3 line quote or paraphrase of the content>

Output only the block, no preamble.
EOF
)

FILTERED=$(claude -p "$FILTER_PROMPT" --model "$MODEL" --output-format text 2>/dev/null | head -c 3000) || exit 0

[ -z "$FILTERED" ] && exit 0
[ "$FILTERED" = "IRRELEVANT" ] && exit 0

# ── Step 5: Emit context block ────────────────────────────────────────
echo "NeoHive smart context (rewriter: $MODEL, hive: ${HIVE:-all}):"
echo "$FILTERED"
